osx install chrome extensions

diff --git a/osx/install b/osx/install
--- a/osx/install
+++ b/osx/install
@@ -227,6 +227,48 @@ function copy_files() {
 # and backup already existing files to the backup folder
 copy_files ~/.dotfiles/osx/user ~ $backup
 
+# install a chrome extension. The installation process is manual (open the extension page on the chrome web store)
+# even if an automatic/silent process is possible and successfully tested. Why? Because:
+# - a locally installed crx will not benefit easily/automatically of the future updates
+# - if you manually uninstall an extension that had been installed silently, this extension is definitly blacklisted
+# http://developer.chrome.com/extensions/external_extensions.html#faq
+# please note there is no safe and simple ways to unsintall an extension, you need to do it manually
+function chrome_extension() {
+    # abort function if Chrome is not installed
+    [[ ! -d '/Applications/Google Chrome.app' ]] && return
+    [[ $# -ne 3 ]] && echo "Runtime error: chrome_extension require 3 arguments" && exit 1
+    # argument 1, the name to be displayed
+    # argument 2, the id of the extension, it also the directory name to check (if directory, it's installed)
+    # argument 3, the URL to open with chrome for launch manual installation
+    local name=$(blue "$1")
+    echo -n -e "Check $name chrome extension..."
+    if [[ ! -d ~/Library/Application\ Support/Google/Chrome/Default/Extensions/$2 ]]; then
+        notok
+        while true; do
+            echo -e -n "Install $name? [Yn]: "
+            read r
+            r=$(echo "$r" | tr '[A-Z]' '[a-z]')
+            case "$r" in
+                y|n) break ;;
+                 '') r='y' && break ;;
+            esac
+        done
+
+        [[ "$r" == 'y' ]] && browser $3
+    else
+        ok
+    fi
+}
+
+chrome_extension 'Adblock Plus'   'cfhdojbkjhnklbpkdaibdccddilifddb' \
+                 'https://chrome.google.com/webstore/detail/empty-title/cfhdojbkjhnklbpkdaibdccddilifddb'
+chrome_extension 'PrettyPrint'    'nipdlgebaanapcphbcidpmmmkcecpkhg' \
+                 'https://chrome.google.com/webstore/detail/prettyprint/nipdlgebaanapcphbcidpmmmkcecpkhg'
+chrome_extension 'JSON Formatter' 'bcjindcccaagfpapjjmafapmmgkkhgoa' \
+                 'https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa'
+chrome_extension 'LiveReload'     'jnihajbhpnppcggbcgedagnkighmdlei' \
+                 'https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei'
+
 # removes some folders if stayed empty
 if [[ $(empty $backup) -eq 1 ]]; then
     echo -e "Delete empty folder $(blue "$backup")" && rm -d $backup
@@ -234,14 +276,3 @@ fi
 if [[ $(empty ~/.dotfiles/.backup) -eq 1 ]]; then
     echo -e "Delete empty folder $(blue "~/.dotfiles/.backup")" && rm -d ~/.dotfiles/.backup
 fi
-
-# function link() {
-#     [[ $# -ne 2 ]] && echo "Runtime error: link require 2 arguments" && exit 1
-#     [[ ! -e "$1" || ! -e "$2" ]] && echo "Runtime error: link require 2 valid paths" && exit 1
-#     if [[ -e "$1" ]]; then
-#         [[ -e "$2" ]] && echo -e "Backup $(blue $2)" && mv "$2" "$backup"
-#         ln -s "$1" "$2" 2>/dev/null
-#         echo -e "Create link $(blue $2)"
-#     fi
-# }
-# link '/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl' ~/.dotfiles/bin/subl
