osx homebrew + formulas install

diff --git a/osx/install b/osx/install
--- a/osx/install
+++ b/osx/install
@@ -5,7 +5,7 @@
 function green() { [[ $# -eq 1 ]] && echo -e "\033[0;32m$1\033[0m"; }
 function red()   { [[ $# -eq 1 ]] && echo -e "\033[0;31m$1\033[0m"; }
 
-# write in blue as a special behavior, will try to reduce path
+# write in blue has a special behavior, will try to reduce path
 # from /Users/username/.dotfiles to ~/.dotfiles
 function blue()  {
     if [[ $# -eq 1 ]]; then
@@ -25,7 +25,7 @@ function blue()  {
     fi
 }
 
-function ok()    { echo -e "$(green KO)"; }
+function ok()    { echo -e "$(green OK)"; }
 function notok() { echo -e "$(red KO)"; }
 
 # check if a folder is empty
@@ -80,7 +80,7 @@ EOF
 }
 
 # check Git
-echo -n 'Check git...'
+echo -n "Check $(blue git)..."
 if [[ ! "$(type -p git)" ]]; then
     notok
     echo 'Aborted: Git must be installed'
@@ -91,7 +91,7 @@ fi
 ok
 
 # check Ruby
-echo -n 'Check ruby...'
+echo -n "Check $(blue ruby)..."
 if [[ ! "$(type -p ruby)" || $(ruby -e "puts RUBY_VERSION >= '1.9.3'") == 'false' ]]; then
     notok
     echo 'Aborted: Ruby must be installed. Version 1.9.3 minimum'
@@ -101,10 +101,108 @@ if [[ ! "$(type -p ruby)" || $(ruby -e "puts RUBY_VERSION >= '1.9.3'") == 'false
 fi
 ok
 
+
+# start of the Homebrew part...
+
+function uninstall_homebrew() {
+    local brew_path=$(type -P brew)
+    echo -n "Uninstall $(blue homebrew)..."
+    if [[ "$brew_path" && -x "$brew_path" ]]; then
+        brew uninstall tree &>/dev/null
+        brew uninstall man2html &>/dev/null
+        brew uninstall phantomjs &>/dev/null
+        # brew prune: remove dead symblink
+        brew prune 1>/dev/null
+        tmp=$(brew --prefix)
+        rm -rf $tmp/bin/brew
+        rm -rf $tmp/Library/brew.rb
+        rm -rf $tmp/Contributions
+        rm -rf $tmp/Cellar
+        rm -rf $tmp/Library
+        rm -rf $tmp/share/man/man1/brew.1
+        rm -rf $tmp/.git
+        ok
+        echo 'Homebrew uninstalled, now exit'
+    else
+        notok
+        echo 'Homebrew seems not installed, now exit'
+    fi
+    # note, use the command below to find installed stuff
+    # find /usr/local -name '*brew*' 2>/dev/null
+    exit
+}
+# ATTENTION
+# code below 'uninstall_homebrew' is for uninstalling Homebrew
+# uncomment only for dev/test
+# uninstall_homebrew
+
+brew_path=$(type -P brew)
+if [[ ! "$brew_path" ]]; then
+    # homebrew is cool but doesn't have an online repository like npm or rubygem
+    # so, all formula (2300+) are downloaded locally via the git repo
+    # and you all history of each formula. Not really cool...
+    # so the installation process is really slow
+    echo "Install $(blue homebrew) (please wait, it's slow)"
+
+    # automatic install (without asking the user keydown)
+    # is only possible with the addition of 'true |'
+    # true | ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
+    
+    # personnal install
+    ruby -e "$(curl -fsSL raw.github.com/jeromedecoster/dotfiles/master/osx/homebrew)"
+
+# is really here, it's an executable?
+# this test is needed after an uninstall
+elif [[ -x "$brew_path" ]]; then
+    echo -n "Update $(blue homebrew)..."
+    # brew update: fetch the newest version of Homebrew
+    # and all formulae from GitHub using git
+    brew update 1>/dev/null
+    if [[ $? -ne 0 ]]; then
+        notok
+        echo 'Failed: Homebrew update return an error'
+    else
+        ok
+    fi
+
+    echo -n "Upgrade $(blue homebrew)..."
+    # brew upgrade: Upgrade outdated, unpinned brews
+    brew upgrade 1>/dev/null
+    if [[ $? -ne 0 ]]; then
+        notok
+        echo 'Failed: Homebrew upgrade return an error'
+    else
+        ok
+    fi
+fi
+
+# Homebrew is installed... now install some forumlas
+
+function install_formula() {
+    if [[ ! $(brew ls -1 | grep -E "^$1$") ]]; then
+        echo -n "Install $(blue $1)..."
+        # redirect stdout and stderr to null, full silence
+        brew install "$1" &>/dev/null
+        if [[ $? -ne 0 ]]; then
+            notok
+            echo "Failed: $1 installation return an error"
+        else
+            ok
+        fi
+    fi
+}
+
+install_formula tree
+install_formula man2html
+install_formula phantomjs
+
+# ...the end of the Homebrew part
+
+
 # update existing ~/.dotfiles repositoy or clone it first the first time
 if [[ -e ~/.dotfiles ]]; then
     cur=$(pwd)
-    echo -n 'Update repository...'
+    echo -n "Update $(blue ~/.dotfiles) repository..."
     cd ~/.dotfiles
     # capture error
     error=$(git pull --quiet 2>&1)
@@ -118,7 +216,7 @@ if [[ -e ~/.dotfiles ]]; then
     fi
     ok
 else
-    echo -n 'Clone repository...'
+    echo -n "Install $(blue ~/.dotfiles) repository..."
     # capture error
     error=$(git clone --quiet https://github.com/jeromedecoster/dotfiles.git ~/.dotfiles 2>&1)
     if [[ $? -ne 0 ]]; then
@@ -133,11 +231,12 @@ fi
 # create backup folder
 backup=~/.dotfiles/.backup/$(date +%Y-%m-%d--%H-%M-%S)
 mkdir -p "$backup"
-# backup=~/.dotfiles-backup
 
-function copy() {
-    [[ $# -ne 2 ]] && echo "Runtime error: copy require 2 arguments" && exit 1
-    [[ ! -e "$1" || ! -e "$2" ]] && echo "Runtime error: copy require 2 valid paths" && exit 1
+function copy_files() {
+    [[ $# -ne 3 ]] && echo "Runtime error: copy require 3 arguments" && exit 1
+    if [[ ! -d "$3" || ! -d "$3" || ! -d "$3" ]]; then
+        echo "Runtime error: copy require 3 valid paths" && exit 1
+    fi
     local name
     for f in $1/{.*,*}; do
         name=$(basename "$f")
@@ -156,7 +255,9 @@ function copy() {
     done
 }
 
-copy ~/.dotfiles/osx/user ~
+# copy files from ~/.dotfiles/osx/user folder to ~
+# and backup already existing files to the backup folder
+copy_files ~/.dotfiles/osx/user ~ $backup
 
 # removes some folders if stayed empty
 if [[ $(empty $backup) -eq 1 ]]; then
